server:
  port: ${PORT:8085}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:8085}  # Valor por defecto si SERVER_URL no está configurado

spring:
  application:
    name: age-detector
  r2dbc:
    url: ${DATABASE_URL}  
    username: ${DATABASE_USERNAME}  
    password: ${DATABASE_PASSWORD} 

rapidapi:
  youtube-mp36:
    url: ${YOUTUBE_API_URL}  
    host: ${YOUTUBE_API_HOST} 
    apikey: ${YOUTUBE_API_KEY}

  instagram120:
    url: ${INSTAGRAM_API_URL}  
    host: ${INSTAGRAM_API_HOST}  
    apikey: ${INSTAGRAM_API_KEY} 

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.web.reactive.function.client: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
