# kubectl apply -f jesus-luyo-08-service.yml
apiVersion: v1
kind: Service
metadata:
  name: api-ai-be
  namespace: jesus-luyo-08
spec:
  type: NodePort      # 30000-32767  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
    - port: 30001       # Puerto que el Service expondrá
      targetPort: 8085  # Puerto en el contenedor donde tu aplicación escucha
      nodePort: 30001   # Puerto asignado en el nodo
  selector:
    app: api-ai-be  # Debe coincidir con las etiquetas del Deployment
